### ISSUE TITLE
The "exp" claim is incorrectly being added to the current time

### ISSUE THREAD

**Issue by arkadyan** [DefactoSoftware/ueberauth_oidc#17]
According to the [spec](https://openid.net/specs/openid-connect-basic-1_0.html#rfc.section.2.2), the "exp" claim is the "Expiration time on or after which the ID Token MUST NOT be accepted for processing." Currently, it is treated like "expires in", and added to the current time. Instead, it should be taken as the expiration time as given.

**Comment by Kuret** [comment]
Fixed in #18
